# frozen_string_literal: true

# Collaborative documents over Action Cable, generated by
# lexxy_realtime:install. Clients join with a signed GlobalID minted by the
# form helper — they never name documents — and every recorded change
# schedules materialization back into Action Text.
class DocumentChannel < ApplicationCable::Channel
  include Y::ActionCable

  on_load { |key| LexxyRealtime.store.load(key) }
  on_change do |key, update|
    # Enqueue BEFORE recording: a failed enqueue raises with nothing recorded,
    # so the client's retransmit retries both (a retransmit of an
    # already-recorded update skips on_change and would never re-enqueue).
    LexxyRealtime::MaterializeJob.set(wait: LexxyRealtime.materialize_after)
                                 .perform_later(record, field) || raise("materialize enqueue failed")
    LexxyRealtime.store.append(key, update)
  end

  def subscribed
    reject and return unless record&.collaborative_rich_text?(field)
    reject and return unless authorized?

    sync_subscribed(record.collaborative_document!(field).id)
  end

  def receive(data)
    return unless record

    sync_receive(data, record.collaborative_document!(field).id)
  end

  private

  # The signed GlobalID proves your app rendered this user the editor for
  # this record; tighten here when page access isn't the whole story
  # (e.g. record.account_id == current_user.account_id).
  def authorized?
    true
  end

  def record
    @record ||= GlobalID::Locator.locate_signed(params[:sgid], for: LexxyRealtime::SGID_PURPOSE)
  end

  def field
    params[:field].to_s
  end
end
