# frozen_string_literal: true

# The collaborative-document channel, generated by lexxy_realtime:install.
#
# A client joins with a signed GlobalID (minted by collaborative_rich_text_area)
# plus the field name; the record and document key are derived server-side, so
# clients never name documents directly and a signed id minted for another
# purpose cannot be replayed here. Every recorded change also schedules
# materialization: the collaborative document is rendered to HTML on the server
# and saved as the record's Action Text body.
class DocumentChannel < ApplicationCable::Channel
  include Y::ActionCable

  on_load { |key| LexxyRealtime.store.load(key) }
  on_change do |key, update|
    # Enqueue BEFORE recording. A failed enqueue (perform_later returns false)
    # raises with nothing recorded, so the client's retransmit retries both —
    # recorded-then-failed-to-enqueue would never retry, because a retransmit
    # of an already-recorded update deliberately skips on_change. The reverse
    # partial failure (enqueued, then append raises) just schedules a harmless
    # extra render: the job is idempotent and debounced.
    LexxyRealtime::MaterializeJob.set(wait: LexxyRealtime.materialize_after)
                                 .perform_later(record, field) || raise("materialize enqueue failed")
    LexxyRealtime.store.append(key, update)
  end

  def subscribed
    reject and return unless record&.collaborative_rich_text?(field)
    reject and return unless authorized?

    sync_subscribed(record.collaborative_document_key(field))
  end

  def receive(data)
    # The key is recomputed from params so any process can handle any frame
    # (under AnyCable each command runs on a fresh channel instance).
    return unless record

    sync_receive(data, record.collaborative_document_key(field))
  end

  private

  # Who may collaborate on this record. The signed GlobalID already proves the
  # client was handed this exact record by your own view; tighten further here
  # when page access isn't the whole story, e.g.:
  #
  #   record.account_id == current_user.account_id
  def authorized?
    true
  end

  def record
    @record ||= GlobalID::Locator.locate_signed(params[:sgid], for: LexxyRealtime.sgid_purpose)
  end

  def field
    params[:field].to_s
  end
end
