// Generates the lexical shim the import-map bundle is built against.
// Bare `lexical` imports inside the bundle (ours and @lexical/yjs's)
// resolve to this module, which hands back Lexxy's embedded copy through
// its documented `Lexical` re-export. The page then runs exactly one
// lexical: the one the editor itself uses. Regenerated on every
// build:importmap from the installed lexical's export list, so it cannot
// drift as lexical adds exports.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const lexical = await import("lexical");

const names = Object.keys(lexical).filter((n) => n !== "default").sort();
const invalid = names.filter((n) => !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n));
if (invalid.length > 0) {
  console.error(`lexical exports that are not plain identifiers: ${invalid.join(", ")}`);
  process.exit(1);
}

const shim = [
  "// Generated by scripts/gen_lexical_shim.mjs. Do not edit.",
  "// Resolves the bundle's bare `lexical` imports to Lexxy's embedded",
  "// copy via its documented `Lexical` re-export: one lexical per page,",
  "// the editor's own.",
  'import { Lexical } from "@37signals/lexxy";',
  ...names.map((n) => `export const ${n} = Lexical.${n};`),
  "",
].join("\n");

const target = join(root, "scripts", "importmap", "lexical_shim.js");
writeFileSync(target, shim);
console.log(`wrote ${target} (${names.length} exports)`);
