// Generates the lexical shim the import-map bundle is built against. Bare
// `lexical` imports in the bundle, ours and @lexical/yjs's, resolve to this
// module. It re-exports Lexxy's embedded copy through Lexxy's documented
// `Lexical` export, so the page loads only the editor's copy of lexical.
// build:importmap regenerates the shim from the installed lexical's export
// list, so new lexical exports are picked up automatically.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const lexical = await import("lexical");

const names = Object.keys(lexical).filter((n) => n !== "default").sort();
const invalid = names.filter((n) => !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n));
if (invalid.length > 0) {
  console.error(`lexical exports that are not plain identifiers: ${invalid.join(", ")}`);
  process.exit(1);
}

const shim = [
  "// Generated by scripts/gen_lexical_shim.mjs. Do not edit.",
  "// Resolves the bundle's bare `lexical` imports to Lexxy's embedded",
  "// copy through its documented `Lexical` export, so the page loads only",
  "// the editor's copy of lexical.",
  'import { Lexical } from "@37signals/lexxy";',
  ...names.map((n) => `export const ${n} = Lexical.${n};`),
  "",
].join("\n");

const target = join(root, "scripts", "importmap", "lexical_shim.js");
writeFileSync(target, shim);
console.log(`wrote ${target} (${names.length} exports)`);
